spring.datasource.url=jdbc:postgresql://192.168.10.95/DEV_home_instruction?currentSchema=homeinstruction
spring.datasource.username=postgres
spring.datasource.password=ada095!

spring.datasource.hikari.minimumIdle=1
spring.datasource.hikari.maximumPoolSize=50
spring.datasource.hikari.idleTimeout=30000

spring.jmx.enabled=false

webSecurity.role=ADMIN
webSecurity.username=admin
webSecurity.password=admin

server.port=8070
api.version=1.0

temp-file-path=E://TempDir


awsUtility.commonUrl=http://192.168.10.81:8080/AWSS3Utility
awsUtility.username=admin
awsUtility.password=admin


spring.servlet.multipart.max-file-size=90MB
spring.servlet.multipart.max-request-size=90MB

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false